<#import "parts/common.ftl" as c>
<@c.page>
<#--    <div>${i18n["message"]}</div>-->
<#--<input class='ua' type=button value='укр' onclick="changeLang('uk_UA')">-->
<#--<input class='eng' type=button value='eng' onclick="changeLang('en')">-->
<#--    <div>${title}</div>-->
<#--    <div>${i18n["${title}"]}</div>-->


    <div class="" style="width: 300px; height: 50px; margin:10% auto;text-align:center">
        <h1><b>${i18n["mainpage.welcome"]}</b></h1>
    </div>

</@c.page>